### ISSUE TITLE
May i know how to reset the setup?

### ISSUE THREAD

**Issue by roimekoi** [timgabets/electron-atm#8]
May i know how to reset the setup?
when i setup the atm host setting, i key in the wrong terminal pin key and terminal master key length, 
when i try to restart the electron-atm simulator i will hit the javascript error
I try to delete the application folder, try to search through regedit and clear browser cache(cookie/ cache) etc but still hit with the same problem.

Thanks in advance

`buffer.js:768 Uncaught TypeError: Invalid hex string
    at Buffer.write (buffer.js:768:21)
    at fromString (buffer.js:212:18)
    at Function.Buffer.from (buffer.js:104:12)
    at new Buffer (buffer.js:85:17)
    at Object.toBuffer (C:\project\ndcsimulator\electron-atm\node_modules\node-cardcrypto\lib\util.js:46:16)
    at Object.des_ecb_encrypt [as ecb_encrypt] (C:\project\ndcsimulator\electron-atm\node_modules\node-cardcrypto\lib\des.js:27:14)
    at CryptoService.getKeyCheckValue (C:/project/ndcsimulator/electron-atm/src/services/crypto.js:47:20)
    at CryptoService.getTerminalKey (C:/project/ndcsimulator/electron-atm/src/services/crypto.js:59:41)
    at CryptoService.getKey (C:/project/ndcsimulator/electron-atm/src/services/crypto.js:78:19)
    at file:///C:/project/ndcsimulator/electron-atm/src/listeners/window.js:196:17`

**Comment by timgabets** [comment]
The [electron-settings](https://www.npmjs.com/package/electron-settings) node module is used to store the app configuration. According to [this](https://github.com/nathanbuchar/electron-settings/wiki/FAQs#where-is-the-settings-file-saved) FAQ, the config is stored somewhere in %APPDATA%/electron-atm. Please, check master_key and pin_key entries in **settings** file there. 

Also, may I ask you to let me know what where the key values, so I could fix the bug?
Many thanks.

**Comment by roimekoi** [comment]
Hi, Sorry i am not able to retrieve the data anymore, 
I think when i try to clear the setup, i executed this function settings.deleteAll() in the console which cause the settings file to have empty {} .
I remember i key in something like this 
1234 123421341234123412341234123
an empty space that does not print the keycheck value
but i still manage to press continue button,

**Comment by timgabets** [comment]
Fixed in 6afb8ca236089380889b4817c32fd835a158d98a - the key input fields are now checked to be [^a-fA-F0-9].

**Comment by timgabets** [comment]
https://github.com/timgabets/electron-atm/releases
